# Copyright (c) 2020, 2023 Diwamoto_
# SPDX-License-Identifier: MIT

description: GPIO keyboard matrix controller

compatible: "zmk,kscan-ec-matrix"

include: kscan.yaml

properties:
  gpios:
    type: phandle-array
    required: true
  adc_channel:
    type: int
    default: 0
  press_point:
    type: int
    default: 100
  release_point:
    type: int
    default: 20