# Copyright (c) 2024 Diwamoto_
# SPDX-License-Identifier: MIT

description: GPIO keyboard matrix controller

compatible: "zmk,kscan-ec-matrix"

include: kscan.yaml

properties:
  gpios:
    type: phandle-array
    required: true
  io-channels:
    type: phandle-array
    required: true
  press_point:
    type: int
    default: 100
  release_point:
    type: int
    default: 20
  active-polling-interval-ms:
    type: int
    default: 8
  idle-polling-interval-ms:
    type: int
    default: 3
  sleep-polling-interval-ms:
    type: int
    default: 3