# Copyright (c) 2024 Diwamoto_
# SPDX-License-Identifier: MIT

description: GPIO keyboard matrix controller

compatible: "zmk,kscan-ec-matrix"

include: kscan.yaml

properties:
  row-gpios:
    type: phandle-array
    required: true
  sel-gpios:
    type: phandle-array
    required: true
  discharge-gpios:
    type: phandle-array
    required: true
  power-gpios:
    type: phandle-array
    required: true
  mux-en-gpios:
    type: phandle-array
    required: true
  col-channels:
    type: array
    required: true
  press-point:
    type: int
    default: 1000
  release-point:
    type: int
    default: 500
  io-channels:
    type: phandle-array
    required: true